// AUTH ACTION TYPES
export const SUCCESSFUL_LOGIN = 'SUCCESSFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOGGING_IN = 'LOGGING_IN';

export const SUCCESSFUL_SIGNIN = 'SUCCESSFUL_SIGNIN';
export const ERROR_SIGNIN = 'ERROR_SIGNIN';
export const SIGNING_IN = 'SIGNING_IN';